const VALIDATION_ERROR = 'validationError';
const VALID_EMAIL_SHOULD_BE_PROVIDED = 'validEmailShouldBeProvided';
const PASSWORD_SHOULD_BE_FROM_SIX_TO_TWENTY_SYMBOLS = 'passwordShouldBeFrom6To20Symbols';
const USER_WITH_EMAIL_DOES_NOT_EXISTS = 'userWithEmailDoesNotExists';
const INVALID_EMAIL_OR_PASSWORD_SPECIFIED = 'invalidEmailOrPasswordSpecified';

export default {
  VALIDATION_ERROR,
  VALID_EMAIL_SHOULD_BE_PROVIDED,
  PASSWORD_SHOULD_BE_FROM_SIX_TO_TWENTY_SYMBOLS,
  USER_WITH_EMAIL_DOES_NOT_EXISTS,
  INVALID_EMAIL_OR_PASSWORD_SPECIFIED,
};
