const EMAIL_ALREADY_IN_USE = 'emailAlreadyInUse';
const FORBIDDEN = 'forbidden';
const INTERNAL_SERVER_ERROR = 'internalServerError';
const INVALID_EMAIL_OR_PASSWORD_SPECIFIED = 'invalidEmailOrPasswordSpecified';
const INVALID_PASSWORD_SPECIFIED = 'invalidPasswordSpecified';
const NAME_SHOULD_BE_FROM_THREE_TO_THIRTY_SYMBOLS = 'nameShouldBeFromThreeToThirtySymbols';
const PASSWORD_CONFIRMATION_SHOULD_MATCH = 'passwordConfirmationShouldMatch';
const PASSWORD_MUST_BE_DIFFERENT_WITH_PREV_ONE = 'passwordMustBeDifferentWithPrevOne';
const PASSWORD_SHOULD_BE_FROM_SIX_TO_TWENTY_SYMBOLS = 'passwordShouldBeFrom6To20Symbols';
const UNAUTHORIZED = 'unauthorized';
const USER_WITH_EMAIL_DOES_NOT_EXISTS = 'userWithEmailDoesNotExists';
const USER_WITH_MAIL_DOES_NOT_EXISTS = 'userWithMailDoesNotExists';
const VALID_EMAIL_SHOULD_BE_PROVIDED = 'validEmailShouldBeProvided';
const VALIDATION_ERROR = 'validationError';

export default {
  EMAIL_ALREADY_IN_USE,
  FORBIDDEN,
  INTERNAL_SERVER_ERROR,
  INVALID_EMAIL_OR_PASSWORD_SPECIFIED,
  INVALID_PASSWORD_SPECIFIED,
  NAME_SHOULD_BE_FROM_THREE_TO_THIRTY_SYMBOLS,
  PASSWORD_CONFIRMATION_SHOULD_MATCH,
  PASSWORD_MUST_BE_DIFFERENT_WITH_PREV_ONE,
  PASSWORD_SHOULD_BE_FROM_SIX_TO_TWENTY_SYMBOLS,
  UNAUTHORIZED,
  USER_WITH_EMAIL_DOES_NOT_EXISTS,
  USER_WITH_MAIL_DOES_NOT_EXISTS,
  VALID_EMAIL_SHOULD_BE_PROVIDED,
  VALIDATION_ERROR,
};
