const VALIDATION_ERROR = 'validationError';
const VALID_EMAIL_SHOULD_BE_PROVIDED = 'validEmailShouldBeProvided';
const PASSWORD_SHOULD_BE_FROM_SIX_TO_TWENTY_SYMBOLS = 'passwordShouldBeFrom6To20Symbols';
const USER_WITH_EMAIL_DOES_NOT_EXISTS = 'userWithEmailDoesNotExists';
const INVALID_EMAIL_OR_PASSWORD_SPECIFIED = 'invalidEmailOrPasswordSpecified';
const NAME_SHOULD_BE_FROM_THREE_TO_THIRTY_SYMBOLS = 'nameShouldBeFromThreeToThirtySymbols';
const PASSWORD_CONFIRMATION_SHOULD_MATCH = 'passwordConfirmationShouldMatch';

export default {
  VALIDATION_ERROR,
  VALID_EMAIL_SHOULD_BE_PROVIDED,
  PASSWORD_SHOULD_BE_FROM_SIX_TO_TWENTY_SYMBOLS,
  USER_WITH_EMAIL_DOES_NOT_EXISTS,
  INVALID_EMAIL_OR_PASSWORD_SPECIFIED,
  NAME_SHOULD_BE_FROM_THREE_TO_THIRTY_SYMBOLS,
  PASSWORD_CONFIRMATION_SHOULD_MATCH,
};
